---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-main-route
spec:
  host: acmeair.apps.ocsm4205001.lnxero1.boe
  path: /acmeair
  to:
    kind: Service
    name: acmeair-main-service
